storeproject/courseapp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('add/', views.student_create_view, name='student_add'),
    path('<int:pk>/', views.student_update_view, name='student_change'),


    path('ajax/load-courses/', views.load_courses, name='ajax_load_courses'),
]

storeproject/regapp/urls.py
from django.urls import path

from . import views

urlpatterns = [

    path('',views.home,name='home1'),
    path('main',views.main,name='main'),
    path('register',views.register, name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),

]

storeproject/storeproject/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('regapp.urls')),
    path('courseapp/',include('courseapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

storeproject/courseapp/models.py
from django.db import models


class Department(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Course(models.Model):
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name



GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other')
    )






class Student(models.Model):
    name = models.CharField(max_length=124)
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, blank=True, null=True)
    course = models.ForeignKey(Course, on_delete=models.SET_NULL, blank=True, null=True)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES)



    def __str__(self):
        return self.name

storeproject/regapp/models.py
from django.db import models

# Create your models here.

storeproject/courseapp/forms.py
from django import forms

from courseapp.models import Student, Course,Department







class StudentCreationForm(forms.ModelForm):
    MATERIAL_CHOICES = (
        ('pen', 'Pen'),
        ('pencil', 'Pencil'),
        ('paper', 'Paper'),
        ('eraser', 'Eraser'),
    )

    materials_provided = forms.MultipleChoiceField(choices=MATERIAL_CHOICES, widget=forms.CheckboxSelectMultiple, label='Materials provided')
    date_of_birth = forms.DateField(label='Date of birth')
    age = forms.IntegerField()
    phone_number = forms.CharField(max_length=20)
    mail_id = forms.EmailField()
    address = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Student
        fields = ['name', 'date_of_birth', 'age', 'phone_number', 'mail_id', 'address', 'department', 'course', 'materials_provided']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['course'].queryset = Course.objects.none()

        if 'department' in self.data:
            try:
                department_id = int(self.data.get('department'))
                self.fields['course'].queryset = Course.objects.filter(department_id=department_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty Course queryset
        elif self.instance.pk:
            self.fields['course'].queryset = self.instance.department.course_set.order_by('name')

storeproject/courseapp/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404

from .forms import StudentCreationForm
from .models import Student, Course


from django.contrib import messages

def student_create_view(request):
    form = StudentCreationForm()
    if request.method == 'POST':
        form = StudentCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Order has been placed successfully!')
            return redirect('student_add')
    return render(request, 'home1.html', {'form': form})


def student_update_view(request, pk):
    student = get_object_or_404(Student, pk=pk)
    form = StudentCreationForm(instance=student)
    if request.method == 'POST':
        form = StudentCreationForm(request.POST, instance=student)
        if form.is_valid():
            form.save()
            return redirect('student_change', pk=pk)
    return render(request, 'home1.html', {'form': form})


# AJAX
def load_courses(request):
    department_id = request.GET.get('department_id')
    courses = Course.objects.filter(department_id=department_id).all()
    return render(request, 'course_dropdown_list_options.html', {'courses': courses})
    # return JsonResponse(list(courses.values('id', 'name')), safe=False)

storeproject/regapp/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect


# Create your views here.
def main(request):
    return render(request, 'main.html')


def home(request):
    return render(request, 'home.html')


def login(request):
    if request.method == "POST":
        username = request.POST['user_name']
        password = request.POST['pass_word']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('courseapp/add/')
        else:
            messages.info(request, "invalid credentials")
            return redirect('login')

    return render(request, 'login.html')


def register(request):
    if request.method == "POST":
        username = request.POST['user_name']
        password = request.POST['pass_word']
        cpassword = request.POST['pass_word1']

        if password == cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request, "Username taken")
                return redirect('register')

            user = User.objects.create_user(username=username, password=password)

            user.save()
            return redirect('login')
        else:
            messages.info(request, "password not matching")
            return redirect('register')
        return redirect('/')
    return render(request, 'register.html')


def logout(request):
    auth.logout(request)
    return redirect('/')

storeproject/courseapp/templates/courseapp/home.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Dependent Dropdown in Django</title>
</head>
<body>





<h2>Student Form</h2>


{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}


<!--<div style="display: inline-block">-->

<!--<form method="post" id="studentForm" data-courses-url="{% url 'ajax_load_courses' %}">-->
<!--    {% csrf_token %}-->
<!--    {{ form.as_p }}-->
<!--    <input type="submit" value="Submit">-->
<!--</form>-->

<!--<button onclick="location.href='{% url 'logout' %}'">Logout</button>-->

<!--</div>-->

<div style="display: inline-block;">
  <form method="post" id="studentForm" data-courses-url="{% url 'ajax_load_courses' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
  </form>
</div>
<div style="display: inline-block;">
  <button onclick="location.href='{% url 'logout' %}'">Logout</button>
</div>












<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_department").change(function () {
        const url = $("#studentForm").attr("data-courses-url");  // get the url of the `load_courses` view
        const departmentId = $(this).val();  // get the selected department ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /students/ajax/load-courses/ )
            data: {
                'department_id': departmentId       // add the department id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_courses` view function
                $("#id_course").html(data);  // replace the contents of the course input with the data that came from the server
                /*

                let html_data = '<option value="">---------</option>';
                data.forEach(function (course) {
                    html_data += `<option value="${course.id}">${course.name}</option>`
                });
                console.log(html_data);
                $("#id_course").html(html_data);

                */
            }
        });

    });
</script>

</body>
</html>

storeproject/templates/course_dropdown_list_options.html
<option value="">---------</option>
{% for course in courses %}
<option value="{{ course.pk }}">{{ course.name }}</option>
{% endfor %}

storeproject/templates/home.html
{% extends 'main.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>home</title>
</head>
<body>
{% block body%}
<h2>HOME</h2>
{% endblock body %}
</body>
</html>

storeproject/templates/home1.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Dependent Dropdown in Django</title>
</head>
<body>





<h2>Student Form</h2>


{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}


<!--<div style="display: inline-block">-->

<!--<form method="post" id="studentForm" data-courses-url="{% url 'ajax_load_courses' %}">-->
<!--    {% csrf_token %}-->
<!--    {{ form.as_p }}-->
<!--    <input type="submit" value="Submit">-->
<!--</form>-->

<!--<button onclick="location.href='{% url 'logout' %}'">Logout</button>-->

<!--</div>-->

<div style="display: inline-block;">
  <form method="post" id="studentForm" data-courses-url="{% url 'ajax_load_courses' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
  </form>
</div>
<div style="display: inline-block;">
  <button onclick="location.href='{% url 'logout' %}'">Logout</button>
</div>












<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_department").change(function () {
        const url = $("#studentForm").attr("data-courses-url");  // get the url of the `load_courses` view
        const departmentId = $(this).val();  // get the selected department ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /students/ajax/load-courses/ )
            data: {
                'department_id': departmentId       // add the department id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_courses` view function
                $("#id_course").html(data);  // replace the contents of the course input with the data that came from the server
                /*

                let html_data = '<option value="">---------</option>';
                data.forEach(function (course) {
                    html_data += `<option value="${course.id}">${course.name}</option>`
                });
                console.log(html_data);
                $("#id_course").html(html_data);

                */
            }
        });

    });
</script>

</body>
</html>

storeproject/templates/login.html
{% extends 'main.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login page</title>
</head>
<body>
{% block body %}
login

<form action="login" method="post">
    {% csrf_token %}
    <input type="text" name="user_name" placeholder="USERNAME"><br>
    <input type="password" name="pass_word" placeholder="PASSWORD"><br>
    <input type="submit">

</form>

{% endblock body %}
</body>
</html>

storeproject/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
logout
</body>
</html>

storeproject/templates/main.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}

    <link rel="stylesheet" href="{% static 'style.css' %}">

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


    <style>
      body {
        background-image: url("{% static 'img/backgroundblue.jpg' %}");
        background-repeat: no-repeat;
        background-size: cover;
      }
    </style>


    <title>Hello, world!</title>
  </head>
  <body style="background-image:url('{% static 'img/backgroundblue.jpg' %}'); background-repeat: no-repeat; background-size: cover;">

<!--  <body style="background-image:url("{% static 'img/backgroundblue.jpg' %}")>-->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="nav-link" href="#">Home</a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">

        {% if user.is_authenticated %}
        <li>Hello {{user.username}}</li>
        <li> <a class="nav-link" href="logout">Logout</a></li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="register">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="login">Login</a>
        </li>
        {% endif %}
<!--        <li class="nav-item">-->
<!--          <a class="nav-link" href="#">Pricing</a>-->
<!--        </li>-->

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Departments
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Chemistry">Chemistry</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Physics">Physics</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Mathematics">Maths</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Music">Music</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Literature">Literature</a>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
  {% block body %}
    <h1>Hello, world!</h1>
  {% endblock body %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

storeproject/templates/register.html
{% extends 'main.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>reg</title>
</head>
<body>
{% block body %}
<h1>register</h1>
<form action="" method="post">
    {% csrf_token %}
    <input type="text" name="user_name" placeholder="USERNAME"><br>
    <input type="password" name="pass_word" placeholder="PASSWORD"><br>
    <input type="password" name="pass_word1" placeholder="CONFIRM PASSWORD"><br>
    <input type="submit">

</form>
{% for msg in messages %}
{{msg}}
{% endfor %}
{% endblock body %}
</body>
</html>